import { QuizQuestion } from "@/components/quiz/QuizEngine";

export interface Quiz {
  title: string;
  questions: QuizQuestion[];
}

export const quizData: Record<string, Quiz> = {
  "grammar-tenses": {
    title: "Les Temps (Tenses)",
    questions: [
      {
        id: 1,
        question: "Conjuguez le verbe 'aller' au présent avec 'nous' :",
        options: ["nous allons", "nous allez", "nous allions", "nous irons"],
        correct: 0,
        explanation: "'Aller' au présent : je vais, tu vas, il va, nous allons, vous allez, ils vont.",
      },
      {
        id: 2,
        question: "Quel est le passé composé de 'je mange' ?",
        options: ["j'ai mangé", "je mangeais", "je mangerai", "j'avais mangé"],
        correct: 0,
        explanation: "Passé composé = auxiliaire (avoir/être) au présent + participe passé.",
      },
      {
        id: 3,
        question: "Complétez : 'Demain, elle ______ (finir) ses devoirs.'",
        options: ["finira", "finit", "a fini", "finissait"],
        correct: 0,
        explanation: "Futur simple de 'finir' : je finirai, tu finiras, il/elle finira...",
      },
      {
        id: 4,
        question: "L'imparfait de 'nous faisons' est :",
        options: ["nous faisions", "nous fîmes", "nous ferons", "nous avons fait"],
        correct: 0,
        explanation: "Imparfait : radical de 'nous' au présent + terminaisons -ais, -ais, -ait, -ions, -iez, -aient.",
      },
      {
        id: 5,
        question: "Quel temps utilise-t-on pour une action habituelle dans le passé ?",
        options: ["L'imparfait", "Le passé composé", "Le futur simple", "Le présent"],
        correct: 0,
        explanation: "L'imparfait décrit des habitudes ou situations dans le passé.",
      },
      {
        id: 6,
        question: "Le participe passé de 'prendre' est :",
        options: ["pris", "prené", "prendu", "prenu"],
        correct: 0,
        explanation: "Participes passés irréguliers : prendre → pris, mettre → mis, faire → fait.",
      },
      {
        id: 7,
        question: "'Ils ______ (venir) hier soir.' — Choisissez le passé composé :",
        options: ["sont venus", "ont venu", "sont venir", "avaient venu"],
        correct: 0,
        explanation: "'Venir' utilise l'auxiliaire 'être' au passé composé. Accord avec le sujet.",
      },
      {
        id: 8,
        question: "Futur simple de 'avoir' avec 'tu' :",
        options: ["tu auras", "tu avais", "tu as eu", "tu aurais"],
        correct: 0,
        explanation: "Futur simple de 'avoir' : j'aurai, tu auras, il aura, nous aurons...",
      },
      {
        id: 9,
        question: "'Elle ______ (être) malade la semaine dernière.' (imparfait)",
        options: ["était", "a été", "sera", "est"],
        correct: 0,
        explanation: "Imparfait de 'être' : j'étais, tu étais, il/elle était...",
      },
      {
        id: 10,
        question: "Quelle phrase est au futur proche ?",
        options: [
          "Je vais partir.",
          "Je partirai.",
          "Je suis parti.",
          "Je partais."
        ],
        correct: 0,
        explanation: "Futur proche = aller (présent) + infinitif. 'Je vais partir' = I am going to leave.",
      },
      {
        id: 11,
        question: "Conjuguez 'pouvoir' au présent avec 'je' :",
        options: ["je peux", "je pouvais", "je pourrai", "je puisse"],
        correct: 0,
        explanation: "Présent de 'pouvoir' : je peux, tu peux, il peut, nous pouvons...",
      },
      {
        id: 12,
        question: "'Nous ______ (sortir) à 8h hier.' — passé composé :",
        options: ["sommes sortis", "avons sorti", "sortons", "sortions"],
        correct: 0,
        explanation: "'Sortir' (intransitif) utilise 'être' : nous sommes sortis.",
      },
      {
        id: 13,
        question: "Le conditionnel présent de 'vouloir' avec 'je' :",
        options: ["je voudrais", "je voulais", "je veux", "je voudrai"],
        correct: 0,
        explanation: "Conditionnel = radical du futur + terminaisons de l'imparfait.",
      },
      {
        id: 14,
        question: "'Les filles ______ (partir) tôt.' — passé composé :",
        options: ["sont parties", "ont parti", "sont partis", "avaient parti"],
        correct: 0,
        explanation: "'Partir' + être → accord féminin pluriel : sont parties.",
      },
      {
        id: 15,
        question: "Quel est l'impératif de 'faire' avec 'nous' ?",
        options: ["faisons", "fais", "faites", "font"],
        correct: 0,
        explanation: "Impératif de 'faire' : fais (tu), faisons (nous), faites (vous).",
      },
    ],
  },
  "grammar-pronouns": {
    title: "Les Pronoms (Pronouns)",
    questions: [
      {
        id: 1,
        question: "Remplacez le COD : 'Je mange la pomme.' →",
        options: ["Je la mange.", "Je lui mange.", "Je le mange.", "Je en mange."],
        correct: 0,
        explanation: "COD féminin singulier 'la pomme' → pronom 'la'. Placé avant le verbe.",
      },
      {
        id: 2,
        question: "'Il parle à Marie.' — Le pronom COI correct est :",
        options: ["Il lui parle.", "Il la parle.", "Il le parle.", "Il y parle."],
        correct: 0,
        explanation: "COI (à + personne) → lui (singulier), leur (pluriel).",
      },
      {
        id: 3,
        question: "Le pronom relatif pour relier : 'C'est le livre. J'ai lu le livre.' →",
        options: ["C'est le livre que j'ai lu.", "C'est le livre qui j'ai lu.", "C'est le livre où j'ai lu.", "C'est le livre dont j'ai lu."],
        correct: 0,
        explanation: "'Que' remplace le COD dans la proposition relative.",
      },
      {
        id: 4,
        question: "'Je vais ______ cinéma.' — Quel pronom remplace 'au cinéma' ?",
        options: ["J'y vais.", "J'en vais.", "Je le vais.", "Je lui vais."],
        correct: 0,
        explanation: "'Y' remplace un lieu introduit par à/au/en/dans.",
      },
      {
        id: 5,
        question: "'Tu veux du café ?' — 'Oui, j'______ veux.'",
        options: ["en", "y", "le", "lui"],
        correct: 0,
        explanation: "'En' remplace un nom introduit par du/de la/des ou une quantité.",
      },
      {
        id: 6,
        question: "Quel pronom relatif : 'La fille ______ chante est ma sœur.'",
        options: ["qui", "que", "où", "dont"],
        correct: 0,
        explanation: "'Qui' = sujet de la proposition relative (la fille chante).",
      },
      {
        id: 7,
        question: "'Je donne les fleurs à mes parents.' → Avec deux pronoms :",
        options: ["Je les leur donne.", "Je leur les donne.", "Je le leur donne.", "Je la leur donne."],
        correct: 0,
        explanation: "Ordre : me/te/nous/vous + le/la/les + lui/leur. Ici 'les' (COD) + 'leur' (COI).",
      },
      {
        id: 8,
        question: "'C'est la ville ______ je suis né.'",
        options: ["où", "qui", "que", "dont"],
        correct: 0,
        explanation: "'Où' indique un lieu ou un moment dans la relative.",
      },
      {
        id: 9,
        question: "'C'est le film ______ je t'ai parlé.'",
        options: ["dont", "que", "qui", "où"],
        correct: 0,
        explanation: "'Dont' remplace 'de + nom'. Parler de → dont.",
      },
      {
        id: 10,
        question: "Pronom tonique après préposition : 'Elle vient avec ______.' (moi)",
        options: ["moi", "me", "je", "mon"],
        correct: 0,
        explanation: "Après une préposition, on utilise les pronoms toniques : moi, toi, lui, elle, nous, vous, eux, elles.",
      },
    ],
  },
  "grammar-adjectives": {
    title: "Les Adjectifs (Adjectives)",
    questions: [
      {
        id: 1,
        question: "Quel est le féminin de 'beau' ?",
        options: ["belle", "beau", "beaux", "belles"],
        correct: 0,
        explanation: "beau → belle (féminin singulier), beaux (masculin pluriel), belles (féminin pluriel).",
      },
      {
        id: 2,
        question: "'Ce ______ livre est intéressant.' (adjectif démonstratif masculin)",
        options: ["ce", "cet", "cette", "ces"],
        correct: 0,
        explanation: "Ce + consonne masculine. Cet + voyelle/h muet masculine. Cette = féminin.",
      },
      {
        id: 3,
        question: "L'adjectif possessif pour 'their book' (masc.) :",
        options: ["leur livre", "leurs livre", "son livre", "ses livre"],
        correct: 0,
        explanation: "Leur (singulier) / Leurs (pluriel) = their. Accord avec l'objet possédé.",
      },
      {
        id: 4,
        question: "Placez l'adjectif : 'une ______ maison ______' (grand/blanc)",
        options: ["une grande maison blanche", "une maison grande blanche", "une blanche grande maison", "une grande blanche maison"],
        correct: 0,
        explanation: "Grand (taille) va avant le nom. Blanc (couleur) va après le nom.",
      },
      {
        id: 5,
        question: "Quel est le pluriel de 'nouveau' ?",
        options: ["nouveaux", "nouvelles", "nouvelle", "nouveaus"],
        correct: 0,
        explanation: "nouveau → nouveaux (masc. pl.), nouvelle → nouvelles (fém. pl.).",
      },
      {
        id: 6,
        question: "'______ arbre est magnifique.' (adjectif démonstratif)",
        options: ["Cet", "Ce", "Cette", "Ces"],
        correct: 0,
        explanation: "'Cet' devant un nom masculin commençant par une voyelle ou un h muet.",
      },
      {
        id: 7,
        question: "L'adjectif possessif pour 'my sister' :",
        options: ["ma sœur", "mon sœur", "mes sœur", "sa sœur"],
        correct: 0,
        explanation: "Ma (féminin singulier) = my. Mon + voyelle féminin (mon amie).",
      },
      {
        id: 8,
        question: "Le féminin de 'vieux' est :",
        options: ["vieille", "vieuxe", "vielle", "vieil"],
        correct: 0,
        explanation: "vieux → vieille (f.s.), vieil (devant voyelle/h muet m.s.).",
      },
      {
        id: 9,
        question: "'C'est une fille ______.' (sportif au féminin)",
        options: ["sportive", "sportife", "sportielle", "sportif"],
        correct: 0,
        explanation: "Adjectifs en -if → féminin -ive : sportif/sportive, actif/active.",
      },
      {
        id: 10,
        question: "'Les garçons sont ______.' (heureux au pluriel)",
        options: ["heureux", "heureuxs", "heureuses", "heureus"],
        correct: 0,
        explanation: "Les adjectifs en -x ne changent pas au masculin pluriel.",
      },
    ],
  },
  "grammar-negation": {
    title: "La Négation (Negation)",
    questions: [
      {
        id: 1,
        question: "Mettez à la forme négative : 'Il mange.'",
        options: ["Il ne mange pas.", "Il mange ne pas.", "Il ne pas mange.", "Il pas ne mange."],
        correct: 0,
        explanation: "Négation : ne + verbe + pas. 'Ne' avant le verbe, 'pas' après.",
      },
      {
        id: 2,
        question: "'Je ne veux ______ manger.' (rien / jamais / plus)",
        options: ["rien", "jamais", "plus", "personne"],
        correct: 0,
        explanation: "Ne...rien = nothing. Je ne veux rien manger = I don't want to eat anything.",
      },
      {
        id: 3,
        question: "'Il ne sort ______.' (never)",
        options: ["jamais", "rien", "plus", "pas"],
        correct: 0,
        explanation: "Ne...jamais = never. Il ne sort jamais = He never goes out.",
      },
      {
        id: 4,
        question: "Forme négative au passé composé : 'J'ai mangé.' →",
        options: ["Je n'ai pas mangé.", "Je n'ai mangé pas.", "Je ne mangé pas ai.", "J'ai ne pas mangé."],
        correct: 0,
        explanation: "Au passé composé : ne + auxiliaire + pas + participe passé.",
      },
      {
        id: 5,
        question: "'Il n'y a ______ dans la salle.' (nobody)",
        options: ["personne", "rien", "jamais", "plus"],
        correct: 0,
        explanation: "Ne...personne = nobody/no one.",
      },
      {
        id: 6,
        question: "'Elle ne mange ______ de viande.' (no more)",
        options: ["plus", "pas", "jamais", "rien"],
        correct: 0,
        explanation: "Ne...plus = no more/no longer.",
      },
      {
        id: 7,
        question: "Avec l'infinitif : 'Il préfère ne pas sortir.' — est-ce correct ?",
        options: ["Oui, c'est correct.", "Non, c'est 'ne sortir pas'.", "Non, c'est 'pas ne sortir'.", "Non, c'est impossible."],
        correct: 0,
        explanation: "Avec l'infinitif, ne pas se placent ensemble AVANT le verbe à l'infinitif.",
      },
      {
        id: 8,
        question: "'______ ne marche.' (Nothing works)",
        options: ["Rien", "Personne", "Jamais", "Plus"],
        correct: 0,
        explanation: "Rien ne... quand 'rien' est sujet. Rien ne marche = Nothing works.",
      },
      {
        id: 9,
        question: "'Je n'ai ______ ami ici.' (not a single / no)",
        options: ["aucun", "pas", "jamais", "rien"],
        correct: 0,
        explanation: "Ne...aucun(e) = not a single / no. Aucun + nom singulier.",
      },
      {
        id: 10,
        question: "Quelle négation est correcte ? 'Elle ne boit ______ thé ______ café.'",
        options: ["ni...ni", "pas...pas", "plus...plus", "rien...rien"],
        correct: 0,
        explanation: "Ne...ni...ni = neither...nor. Elle ne boit ni thé ni café.",
      },
    ],
  },
  "vocabulary-ch1-4": {
    title: "Vocabulaire — Leçons 1-4",
    questions: [
      { id: 1, question: "'La rentrée' signifie :", options: ["Back to school", "Holiday", "Birthday", "Weekend"], correct: 0, explanation: "La rentrée = the start of the school year / back to school." },
      { id: 2, question: "Traduisez 'faire les courses' :", options: ["To go shopping", "To run", "To cook", "To study"], correct: 0, explanation: "Faire les courses = to go grocery shopping." },
      { id: 3, question: "'Un copain' veut dire :", options: ["A friend (informal)", "A teacher", "A cousin", "A neighbor"], correct: 0, explanation: "Un copain / une copine = a friend (informal/casual)." },
      { id: 4, question: "'L'emploi du temps' signifie :", options: ["Timetable/schedule", "Employment", "Free time", "Homework"], correct: 0, explanation: "L'emploi du temps = timetable / class schedule." },
      { id: 5, question: "Que veut dire 'réussir un examen' ?", options: ["To pass an exam", "To fail an exam", "To take an exam", "To study for an exam"], correct: 0, explanation: "Réussir = to succeed/pass. Échouer = to fail." },
      { id: 6, question: "'Le quartier' signifie :", options: ["Neighbourhood", "Quarter (time)", "School", "Country"], correct: 0, explanation: "Le quartier = neighbourhood / area of a city." },
      { id: 7, question: "Traduisez 'avoir envie de' :", options: ["To feel like / to want", "To be afraid of", "To need", "To have to"], correct: 0, explanation: "Avoir envie de = to feel like doing something." },
      { id: 8, question: "'Déménager' veut dire :", options: ["To move (house)", "To eat", "To manage", "To start"], correct: 0, explanation: "Déménager = to move house. Emménager = to move in." },
      { id: 9, question: "'Un séjour' peut signifier :", options: ["A stay / living room", "A journey", "A meal", "An office"], correct: 0, explanation: "Un séjour = a stay (at a place) or a living room." },
      { id: 10, question: "'Bavard(e)' décrit une personne qui :", options: ["Talks a lot", "Is shy", "Is angry", "Is lazy"], correct: 0, explanation: "Bavard/bavarde = talkative / chatty." },
      { id: 11, question: "'La matière préférée' signifie :", options: ["Favourite subject", "Favourite material", "Best mark", "First class"], correct: 0, explanation: "La matière = school subject. Matière préférée = favourite subject." },
      { id: 12, question: "Traduisez 'se lever tôt' :", options: ["To wake up early", "To go to bed early", "To get dressed", "To eat breakfast"], correct: 0, explanation: "Se lever = to get up. Tôt = early." },
      { id: 13, question: "'Les vacances' veut dire :", options: ["Holidays/vacation", "Vaccine", "Vacant", "Vegetables"], correct: 0, explanation: "Les vacances (always plural) = holidays / vacation." },
      { id: 14, question: "Que signifie 'un cadeau' ?", options: ["A gift", "A cake", "A box", "A card"], correct: 0, explanation: "Un cadeau = a gift/present. Plural: des cadeaux." },
      { id: 15, question: "'S'amuser' signifie :", options: ["To have fun", "To be bored", "To get angry", "To be amused"], correct: 0, explanation: "S'amuser = to have fun / enjoy oneself." },
      { id: 16, question: "'Le collège' en France, c'est :", options: ["Middle school (ages 11-15)", "University", "Primary school", "High school"], correct: 0, explanation: "Le collège = middle school. Le lycée = high school." },
      { id: 17, question: "Traduisez 'avoir besoin de' :", options: ["To need", "To want", "To be able to", "To have to"], correct: 0, explanation: "Avoir besoin de = to need. J'ai besoin d'un stylo." },
      { id: 18, question: "'Ranger sa chambre' signifie :", options: ["To tidy one's room", "To paint one's room", "To leave one's room", "To share one's room"], correct: 0, explanation: "Ranger = to tidy up / put away." },
      { id: 19, question: "'Un voisin' est :", options: ["A neighbour", "A cousin", "A friend", "A visitor"], correct: 0, explanation: "Un voisin / une voisine = a neighbour." },
      { id: 20, question: "'Être en retard' signifie :", options: ["To be late", "To be early", "To be tired", "To be ready"], correct: 0, explanation: "En retard = late. En avance = early. À l'heure = on time." },
    ],
  },
  "vocabulary-ch5-8": {
    title: "Vocabulaire — Leçons 5-8",
    questions: [
      { id: 1, question: "'La santé' signifie :", options: ["Health", "Santa", "Safety", "Salary"], correct: 0 },
      { id: 2, question: "Traduisez 'un repas' :", options: ["A meal", "A rest", "A repair", "A trip"], correct: 0 },
      { id: 3, question: "'Faire la cuisine' veut dire :", options: ["To cook", "To clean", "To eat out", "To wash dishes"], correct: 0 },
      { id: 4, question: "'Une recette' signifie :", options: ["A recipe", "A receipt", "A request", "A rest"], correct: 0 },
      { id: 5, question: "Que veut dire 'le marché' ?", options: ["The market", "The march", "The brand", "The step"], correct: 0 },
      { id: 6, question: "'Goûter' signifie :", options: ["To taste/afternoon snack", "To go out", "To get up", "To swim"], correct: 0 },
      { id: 7, question: "Traduisez 'les légumes' :", options: ["Vegetables", "Laws", "Legends", "Legs"], correct: 0 },
      { id: 8, question: "'La boulangerie' est un magasin qui vend :", options: ["Bread & pastries", "Meat", "Books", "Flowers"], correct: 0 },
      { id: 9, question: "'Tomber malade' signifie :", options: ["To fall ill", "To fall down", "To make someone ill", "To recover"], correct: 0 },
      { id: 10, question: "'Le médecin' est :", options: ["The doctor", "The medicine", "The medium", "The mediator"], correct: 0 },
      { id: 11, question: "'Avoir mal à la tête' signifie :", options: ["To have a headache", "To have a bad head", "To be angry", "To be confused"], correct: 0 },
      { id: 12, question: "Traduisez 'les transports en commun' :", options: ["Public transport", "Common transfers", "Community travels", "Transport charges"], correct: 0 },
      { id: 13, question: "'Un métier' signifie :", options: ["A profession/job", "A metro", "A meter", "A method"], correct: 0 },
      { id: 14, question: "'Économiser' veut dire :", options: ["To save (money)", "To economize time", "To eat", "To exercise"], correct: 0 },
      { id: 15, question: "'L'environnement' signifie :", options: ["The environment", "The surroundings only", "The city", "The entertainment"], correct: 0 },
      { id: 16, question: "Traduisez 'une île' :", options: ["An island", "An aisle", "A street", "A hill"], correct: 0 },
      { id: 17, question: "'Le patrimoine' signifie :", options: ["Heritage/patrimony", "The father", "The homeland", "The pattern"], correct: 0 },
      { id: 18, question: "'Se déplacer' veut dire :", options: ["To get around/travel", "To displace something", "To display", "To be displaced"], correct: 0 },
      { id: 19, question: "'Un stage' signifie :", options: ["An internship/training", "A stage (theatre)", "A floor/level", "A state"], correct: 0 },
      { id: 20, question: "'La mode' signifie :", options: ["Fashion", "Mood", "Model", "Mode (way)"], correct: 0 },
    ],
  },
  "vocabulary-ch9-12": {
    title: "Vocabulaire — Leçons 9-12",
    questions: [
      { id: 1, question: "'Le voyage' signifie :", options: ["The trip/journey", "The voice", "The village", "The view"], correct: 0 },
      { id: 2, question: "Traduisez 'un billet' :", options: ["A ticket", "A bill", "A bullet", "A ballet"], correct: 0 },
      { id: 3, question: "'L'avenir' signifie :", options: ["The future", "The adventure", "The avenue", "The arrival"], correct: 0 },
      { id: 4, question: "'Rêver de' veut dire :", options: ["To dream of", "To review", "To return from", "To revise"], correct: 0 },
      { id: 5, question: "'La fête' signifie :", options: ["The celebration/party", "The feet", "The fate", "The fact"], correct: 0 },
      { id: 6, question: "Traduisez 'un séjour à l'étranger' :", options: ["A stay abroad", "A foreign room", "A strange stay", "An overseas job"], correct: 0 },
      { id: 7, question: "'Découvrir' veut dire :", options: ["To discover", "To uncover", "To decorate", "To discourage"], correct: 0 },
      { id: 8, question: "'La planète' signifie :", options: ["The planet", "The plant", "The plane", "The plan"], correct: 0 },
      { id: 9, question: "'Protéger la nature' signifie :", options: ["To protect nature", "To protest nature", "To provide nature", "To produce nature"], correct: 0 },
      { id: 10, question: "'Un souvenir' signifie :", options: ["A memory/souvenir", "A supper", "A surprise", "A subway"], correct: 0 },
      { id: 11, question: "'Le paysage' signifie :", options: ["The landscape", "The passage", "The passenger", "The page"], correct: 0 },
      { id: 12, question: "Traduisez 'réserver une chambre' :", options: ["To book a room", "To reserve a seat", "To restore a chamber", "To resign a room"], correct: 0 },
      { id: 13, question: "'La gare' signifie :", options: ["The train station", "The garage", "The garden", "The gate"], correct: 0 },
      { id: 14, question: "'Un passeport' est nécessaire pour :", options: ["Voyager à l'étranger", "Aller à l'école", "Faire les courses", "Prendre le bus"], correct: 0 },
      { id: 15, question: "'La pollution' signifie :", options: ["Pollution", "Policy", "Polish", "Population"], correct: 0 },
      { id: 16, question: "Traduisez 'les déchets' :", options: ["Waste/rubbish", "The dishes", "The decisions", "The discoveries"], correct: 0 },
      { id: 17, question: "'Économiser l'eau' veut dire :", options: ["To save water", "To heat water", "To drink water", "To pollute water"], correct: 0 },
      { id: 18, question: "'Le réchauffement climatique' signifie :", options: ["Global warming", "Climate cooling", "Weather forecast", "Heat wave"], correct: 0 },
      { id: 19, question: "'Un hébergement' signifie :", options: ["Accommodation", "Heritage", "Herb garden", "Heroism"], correct: 0 },
      { id: 20, question: "'Faire ses valises' veut dire :", options: ["To pack one's bags", "To make valleys", "To do laundry", "To buy suitcases"], correct: 0 },
    ],
  },
  "comprehension": {
    title: "Compréhension (Reading)",
    questions: [
      { id: 1, question: "Dans un passage, 'il fait beau' signifie :", options: ["The weather is nice", "He is handsome", "It is expensive", "He makes beauty"], correct: 0 },
      { id: 2, question: "'Je suis en train de lire' signifie :", options: ["I am reading (right now)", "I am on the train reading", "I was reading", "I will read"], correct: 0 },
      { id: 3, question: "Quel mot interrogatif pour demander 'why' ?", options: ["Pourquoi", "Comment", "Quand", "Combien"], correct: 0 },
      { id: 4, question: "'D'après le texte' signifie :", options: ["According to the text", "After the text", "Before the text", "Despite the text"], correct: 0 },
      { id: 5, question: "'Il s'agit de...' signifie :", options: ["It is about...", "He acts like...", "It is against...", "He agrees with..."], correct: 0 },
      { id: 6, question: "'Cependant' est un synonyme de :", options: ["However", "Therefore", "Because", "Finally"], correct: 0 },
      { id: 7, question: "'En effet' signifie :", options: ["Indeed / In fact", "In effect only", "Effectively done", "After effect"], correct: 0 },
      { id: 8, question: "Si le texte dit 'il pleut', quel temps fait-il ?", options: ["It is raining", "It is snowing", "It is sunny", "It is windy"], correct: 0 },
      { id: 9, question: "'Grâce à' signifie :", options: ["Thanks to", "Grace of", "In spite of", "Because of (negative)"], correct: 0 },
      { id: 10, question: "'Par contre' signifie :", options: ["On the other hand", "By counting", "For example", "As a result"], correct: 0 },
    ],
  },
};
